import Movie from "./models/Movie.js";

const IMG = "https://image.tmdb.org/t/p/w500";
const BAN = "https://image.tmdb.org/t/p/original";

const makeShowtimes = (prices = [250, 300, 350]) => [
  { date: "2026-04-05", time: "10:00 AM", hall: "IMAX 1", price: prices[2], totalSeats: 60, bookedSeats: [] },
  { date: "2026-04-05", time: "01:30 PM", hall: "Hall 2", price: prices[1], totalSeats: 60, bookedSeats: [] },
  { date: "2026-04-05", time: "06:00 PM", hall: "IMAX 1", price: prices[2], totalSeats: 60, bookedSeats: [] },
  { date: "2026-04-06", time: "11:00 AM", hall: "Hall 3", price: prices[0], totalSeats: 60, bookedSeats: [] },
  { date: "2026-04-06", time: "03:30 PM", hall: "Hall 1", price: prices[1], totalSeats: 60, bookedSeats: [] },
];

const movies = [
  {
    title: "Interstellar",
    description: "A group of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. A visually stunning and emotionally gripping sci-fi masterpiece.",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    duration: 169,
    rating: 8.7,
    poster: `${IMG}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`,
    banner: `${BAN}/xJHokMbljvjADYdit5fK1DVfjko.jpg`,
    releaseDate: "2014-11-07",
    language: "English",
    showtimes: makeShowtimes([250, 300, 400]),
  },
  {
    title: "The Batman",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    genre: ["Action", "Crime", "Drama"],
    duration: 176,
    rating: 7.8,
    poster: `${IMG}/74xTEgt7R36Fpooo50r9T25onhq.jpg`,
    banner: `${BAN}/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg`,
    releaseDate: "2022-03-04",
    language: "English",
    showtimes: makeShowtimes([200, 250, 380]),
  },
  {
    title: "Dune: Part Two",
    description: "Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. He faces a choice between the love of his life and the fate of the universe.",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    duration: 166,
    rating: 8.5,
    poster: `${IMG}/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg`,
    banner: `${BAN}/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg`,
    releaseDate: "2024-03-01",
    language: "English",
    showtimes: makeShowtimes([280, 350, 450]),
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    genre: ["Animation", "Action", "Adventure"],
    duration: 140,
    rating: 8.6,
    poster: `${IMG}/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg`,
    banner: `${BAN}/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg`,
    releaseDate: "2023-06-02",
    language: "English",
    showtimes: makeShowtimes([220, 280, 350]),
  },
  {
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    genre: ["Biography", "Drama", "History"],
    duration: 180,
    rating: 8.4,
    poster: `${IMG}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`,
    banner: `${BAN}/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg`,
    releaseDate: "2023-07-21",
    language: "English",
    showtimes: makeShowtimes([250, 300, 420]),
  },
  {
    title: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    genre: ["Action", "Thriller", "Crime"],
    duration: 169,
    rating: 7.7,
    poster: `${IMG}/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg`,
    banner: `${BAN}/7I6VUdPj6tQECNHdviJkUHD2u89.jpg`,
    releaseDate: "2023-03-24",
    language: "English",
    showtimes: makeShowtimes([200, 250, 380]),
  },
  // ---- 20 NEW MOVIES BELOW ----
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genre: ["Action", "Crime", "Drama"],
    duration: 152,
    rating: 9.0,
    poster: `${IMG}/d5NXSklXo0qyIYkgV94XAgMIckC.jpg`,
    banner: `${BAN}/nMKdUUepR0i5zn0y1T4CsSB5eze.jpg`,
    releaseDate: "2008-07-18",
    language: "English",
    showtimes: makeShowtimes([200, 280, 380]),
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genre: ["Sci-Fi", "Action", "Thriller"],
    duration: 148,
    rating: 8.8,
    poster: `${IMG}/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg`,
    banner: `${BAN}/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg`,
    releaseDate: "2010-07-16",
    language: "English",
    showtimes: makeShowtimes([220, 300, 400]),
  },
  {
    title: "Avengers: Endgame",
    description: "After the devastating events of Infinity War, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    duration: 181,
    rating: 8.4,
    poster: `${IMG}/or06FN3Dka5tukK1e9sl16pB3iy.jpg`,
    banner: `${BAN}/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg`,
    releaseDate: "2019-04-26",
    language: "English",
    showtimes: makeShowtimes([250, 320, 420]),
  },
  {
    title: "Joker",
    description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    genre: ["Crime", "Drama", "Thriller"],
    duration: 122,
    rating: 8.4,
    poster: `${IMG}/NNxYkU70HPurnNCSiCjYAmacwm.jpg`,
    banner: `${BAN}/n6bUvigpRFqSwmPp1m2YMDm2A75.jpg`,
    releaseDate: "2019-10-04",
    language: "English",
    showtimes: makeShowtimes([200, 260, 350]),
  },
  {
    title: "Barbie",
    description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they discover the joys and perils of living among humans.",
    genre: ["Comedy", "Adventure", "Fantasy"],
    duration: 114,
    rating: 6.9,
    poster: `${IMG}/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg`,
    banner: `${BAN}/nHf61UzkfFno5X1ofIhugCPus2R.jpg`,
    releaseDate: "2023-07-21",
    language: "English",
    showtimes: makeShowtimes([180, 220, 300]),
  },
  {
    title: "Deadpool & Wolverine",
    description: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
    genre: ["Action", "Comedy", "Sci-Fi"],
    duration: 128,
    rating: 7.7,
    poster: `${IMG}/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg`,
    banner: `${BAN}/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg`,
    releaseDate: "2024-07-26",
    language: "English",
    showtimes: makeShowtimes([250, 320, 400]),
  },
  {
    title: "Gladiator II",
    description: "Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum to fight for the honor of Rome.",
    genre: ["Action", "Adventure", "Drama"],
    duration: 148,
    rating: 6.8,
    poster: `${IMG}/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg`,
    banner: `${BAN}/euYIwmwkmz95mnXvufEoKeN7qII.jpg`,
    releaseDate: "2024-11-22",
    language: "English",
    showtimes: makeShowtimes([250, 300, 400]),
  },
  {
    title: "Avatar",
    description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    genre: ["Sci-Fi", "Action", "Adventure"],
    duration: 162,
    rating: 7.9,
    poster: `${IMG}/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg`,
    banner: `${BAN}/o0s4XsEDfDlvit5pDRKjzXR4zN0.jpg`,
    releaseDate: "2009-12-18",
    language: "English",
    showtimes: makeShowtimes([250, 300, 420]),
  },
  {
    title: "Top Gun: Maverick",
    description: "After more than thirty years of service, Navy aviator Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank.",
    genre: ["Action", "Drama"],
    duration: 130,
    rating: 8.2,
    poster: `${IMG}/q719jXXEzOoYaps6babgKnONONX.jpg`,
    banner: `${BAN}/AaV1YIdWKRiEIPHFMhOiMUBx94b.jpg`,
    releaseDate: "2022-05-27",
    language: "English",
    showtimes: makeShowtimes([220, 280, 380]),
  },
  {
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    genre: ["Sci-Fi", "Action"],
    duration: 136,
    rating: 8.7,
    poster: `${IMG}/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg`,
    banner: `${BAN}/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg`,
    releaseDate: "1999-03-31",
    language: "English",
    showtimes: makeShowtimes([180, 220, 300]),
  },
  {
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    genre: ["Crime", "Drama"],
    duration: 175,
    rating: 9.2,
    poster: `${IMG}/3bhkrj58Vtu7enYsRolD1fZdja1.jpg`,
    banner: `${BAN}/tmU7GeKVybMWFButWEGl2M4GeiP.jpg`,
    releaseDate: "1972-03-24",
    language: "English",
    showtimes: makeShowtimes([200, 250, 350]),
  },
  {
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    genre: ["Crime", "Drama", "Thriller"],
    duration: 154,
    rating: 8.9,
    poster: `${IMG}/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg`,
    banner: `${BAN}/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg`,
    releaseDate: "1994-10-14",
    language: "English",
    showtimes: makeShowtimes([180, 220, 300]),
  },
  {
    title: "Mad Max: Fury Road",
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a drifter named Max.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    duration: 120,
    rating: 8.1,
    poster: `${IMG}/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg`,
    banner: `${BAN}/nlCHUWjY9XWbuEUQauCBgnY8bmN.jpg`,
    releaseDate: "2015-05-15",
    language: "English",
    showtimes: makeShowtimes([200, 260, 350]),
  },
  {
    title: "Guardians of the Galaxy Vol. 3",
    description: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own. A mission that could mean the end of the Guardians if not successful.",
    genre: ["Action", "Adventure", "Comedy"],
    duration: 150,
    rating: 7.9,
    poster: `${IMG}/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg`,
    banner: `${BAN}/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg`,
    releaseDate: "2023-05-05",
    language: "English",
    showtimes: makeShowtimes([220, 280, 380]),
  },
  {
    title: "Joker: Folie a Deux",
    description: "Arthur Fleck is institutionalized at Arkham awaiting trial for his crimes as Joker. While struggling with his dual identity, he stumbles upon true love and music.",
    genre: ["Crime", "Drama", "Musical"],
    duration: 138,
    rating: 5.5,
    poster: `${IMG}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg`,
    banner: `${BAN}/op3R7xBhGfJFCuQqJyHEEhf45Xc.jpg`,
    releaseDate: "2024-10-04",
    language: "English",
    showtimes: makeShowtimes([200, 260, 350]),
  },
  {
    title: "Tenet",
    description: "Armed with only one word — Tenet — and fighting for the survival of the world, a protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    genre: ["Sci-Fi", "Action", "Thriller"],
    duration: 150,
    rating: 7.3,
    poster: `${IMG}/k68nPLbIST6NP96JmTxmZijEvCA.jpg`,
    banner: `${BAN}/628Dep6AxEtDxjZoGP78TsOxYbK.jpg`,
    releaseDate: "2020-09-03",
    language: "English",
    showtimes: makeShowtimes([220, 280, 380]),
  },
  {
    title: "Shutter Island",
    description: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane on a remote island.",
    genre: ["Thriller", "Mystery", "Drama"],
    duration: 138,
    rating: 8.2,
    poster: `${IMG}/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg`,
    banner: `${BAN}/hUfAZBplAyBz4lPGCyRcaVi3JJE.jpg`,
    releaseDate: "2010-02-19",
    language: "English",
    showtimes: makeShowtimes([180, 220, 300]),
  },
  {
    title: "Bohemian Rhapsody",
    description: "The story of the legendary British rock band Queen and lead singer Freddie Mercury, leading up to their famous performance at Live Aid in 1985.",
    genre: ["Biography", "Drama", "Music"],
    duration: 134,
    rating: 7.9,
    poster: `${IMG}/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg`,
    banner: `${BAN}/93xA62uLd5CwMOAs37eQ1WgsVVK.jpg`,
    releaseDate: "2018-11-02",
    language: "English",
    showtimes: makeShowtimes([200, 250, 320]),
  },
  {
    title: "Blade Runner 2049",
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    genre: ["Sci-Fi", "Drama", "Thriller"],
    duration: 164,
    rating: 8.0,
    poster: `${IMG}/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg`,
    banner: `${BAN}/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg`,
    releaseDate: "2017-10-06",
    language: "English",
    showtimes: makeShowtimes([220, 280, 380]),
  },
  {
    title: "Wonka",
    description: "Armed with nothing but a hatful of dreams and a pocketful of chocolate, young Willy Wonka sets out to open a shop in a city renowned for its chocolate — but faces opposition from established chocolatiers.",
    genre: ["Comedy", "Family", "Fantasy"],
    duration: 116,
    rating: 7.1,
    poster: `${IMG}/qhb1qOilapbapxWQn9jtRCMwXJF.jpg`,
    banner: `${BAN}/dOJrpSfKBsJADkg6onrDYUXJfHr.jpg`,
    releaseDate: "2023-12-15",
    language: "English",
    showtimes: makeShowtimes([180, 220, 300]),
  },
];

export async function seedMovies() {
  const count = await Movie.countDocuments();
  if (count === 0) {
    await Movie.insertMany(movies);
    console.log(`Database seeded with ${movies.length} movies`);
  }
}
